import type { Game } from '@/lib/types';
import { BrainCircuit, Puzzle, Zap, GitCommitHorizontal, Hammer, X, Rows4, MoveHorizontal, Bomb, Star, CaseSensitive, Scissors, VenetianMask, Pointer, Dice5 } from 'lucide-react';

export const GAMES: Game[] = [
  {
    id: 'quick-reaction',
    name: 'Quick Reaction',
    description: 'How fast are your reflexes? Click when ready!',
    icon: Zap,
    href: '/games/quick-reaction',
  },
  {
    id: 'puzzle',
    name: 'Sliding Puzzle',
    description: 'Slide the tiles to solve the puzzle.',
    icon: Puzzle,
    href: '/games/puzzle',
  },
  {
    id: 'snake',
    name: 'Snake',
    description: 'Guide the snake to eat the food and grow.',
    icon: GitCommitHorizontal,
    href: '/games/snake',
  },
  {
    id: 'whack-a-mole',
    name: 'Whack-a-Mole',
    description: 'Test your reflexes and whack the moles!',
    icon: Hammer,
    href: '/games/whack-a-mole',
  },
  {
    id: 'tic-tac-toe',
    name: 'Tic-Tac-Toe',
    description: 'The classic game of Xs and Os.',
    icon: X,
    href: '/games/tic-tac-toe',
  },
  {
    id: 'connect-four',
    name: 'Connect Four',
    description: 'Get four of your discs in a row to win.',
    icon: Rows4,
    href: '/games/connect-four',
  },
  {
    id: 'pong',
    name: 'Pong',
    description: 'The original paddle and ball game.',
    icon: MoveHorizontal,
    href: '/games/pong',
  },
  {
    id: 'minesweeper',
    name: 'Minesweeper',
    description: 'Clear the board without hitting a mine.',
    icon: Bomb,
    href: '/games/minesweeper',
  },
  {
    id: 'memory-match',
    name: 'Memory Match',
    description: 'Flip cards to find matching pairs.',
    icon: Star,
    href: '/games/memory-match',
  },
  {
    id: 'word-scramble',
    name: 'Word Scramble',
    description: 'Unscramble the letters to form a word.',
    icon: CaseSensitive,
    href: '/games/word-scramble',
  },
  {
    id: 'rock-paper-scissors',
    name: 'Rock Paper Scissors',
    description: 'The classic game of choices. Can you beat the AI?',
    icon: Scissors,
    href: '/games/rock-paper-scissors',
  },
  {
    id: 'hangman',
    name: 'Hangman',
    description: 'Guess the word before it\'s too late.',
    icon: VenetianMask,
    href: '/games/hangman',
  },
  {
    id: 'simon-says',
    name: 'Simon Says',
    description: 'Repeat the pattern of colors and sounds.',
    icon: Dice5,
    href: '/games/simon-says',
  },
  {
    id: 'brick-breaker',
    name: 'Brick Breaker',
    description: 'Break all the bricks to win.',
    icon: Pointer,
    href: '/games/brick-breaker',
  },
];
